### ISSUE TITLE
Issue with LlamaParse: Hallucinations on Bank Statements

### ISSUE THREAD

**Issue by bsuttonvyde** [run-llama/llama_parse#450]
_Note: we're aware of some missing content in the output and layout issues on tables. Please refrain from opening new issues on this topic unless if you think it's different from what has already been reported._

**Describe the bug**
I am parsing 4-10 page bank statements with "Accurate" mode and it is creating transactions that don't exist on the original bank statement document.  

**Files**
I'd prefer not to upload the document as it has personally identifiable information. 

**Job ID**
8e57c117-1263-4eed-9131-3a50c05c12ee

**Options**
I used "Accurate" mode with parsing instructions.

**Comment by bsuttonvyde** [comment]
Does the use of parsing instructions increase the likelihood of hallucinations?

**Comment by BinaryBrain** [comment]
It does because we give a high priority to your prompt compare to our default formatting. We've just released a flag that could help you: https://docs.cloud.llamaindex.ai/llamaparse/features/parsing_options#is-formatting-instruction

It's enabled by default but if you disable it, you should have a cleaner markdown with less to none hallucinations.
Also, if your prompt is too long, it can actually decrease the quality of the output because of the lack of attention of the model.
